options:
  version:
    type: string
    default: "0.5.0"
    description: "The version of Consul software to install, default is '0.5.0'"
  log-level:
    type: string
    default: "info"
    description: "The level of logging to show after the Consul agent has
      started. This defaults to 'info'. The available log levels are 'trace',
      'debug', 'info', 'warn', and 'err'. Note that you can always connect to
      an agent via consul monitor and use any log level."
  domain:
    type: string
    default: "consul"
    description: "By default, Consul responds to DNS queries in the 'consul.
      domain. This flag can be used to change that domain. All queries in this
      domain are assumed to be handled by Consul and will not be recursively
      resolved."
#
#  encrypt:
#    type: boolean
#    default: false
#    description: "Encrypt all communications"
#
#  disable-exec:
#    type: boolean
#    default: false
#    description: "Disable remote execution through consul"
